#!/bin/bash


i="y"
while [ $i = "y" ]
do

echo -n "escolha o primeiro numero: "; read num1
echo -n "escolha a operacao ' - + * / x ': "; read op
echo -n "escolha o segundo numero: "; read num2

if [ "$op" = '-' ];
echo "$(($num1 - $num2))"
elif [ "$op" = '+' ];
echo "$(($num1 + $num2))"
elif [ "$op" = '*' ];
echo "$(($num1 * $num2))"
elif [ "$op" = 'x' ];
echo "$(($num1 * $num2))"
elif [ "$op" = '/' ];
echo "$(($num1 / $num2))"

else
echo "Escolha uma opção valida"
exit 1
fi

echo "Voce quer continuar (y/n)?"
read i
if[$i!= "y" ]
exit
fi
done
